#!/bin/bash

script=mgr2
command=$1
repo_list_name=$2

if [ ! -d ~/.$script ]; then
    mkdir ~/.$script
fi

if [ ! -f ~/.$script/default.pull ]; then
    touch ~/.$script/default.pull
fi

if [ ! -f ~/.$script/default.push ]; then
    touch ~/.$script/default.push
fi

case $command in
    "") echo "$script: missing command"
        exit $E_PARAM
        ;;
    add|rm)
        case $repo_list_name in
            "") echo "$script: missing repository list name"
                exit $E_PARAM
                ;;
            *[!a-zA-Z0-9_]*)
                echo "$script: invalid repository list name"
                exit $E_PARAM
                ;;
            pull|push)
                repo_list_file_name=~/.$script/default.$repo_list_name
                ;;
            *)
                repo_list_file_name=~/.$script/$repo_list_name.list
                ;;
        esac
        ;;&
    add)
        touch $repo_list_file_name
        pwd | sort --unique --merge - $repo_list_file_name --output=$repo_list_file_name
        ;;
    rm)
        sed "\|`pwd`|d" $repo_list_file_name --in-place
        ;;
    pull|push)
        case $repo_list_name in
            *[!a-zA-Z0-9_]*)
                echo "$script: invalid repository list name"
                exit $E_PARAM
                ;;
            "")
                repo_list_file_name=~/.$script/default.$command
                ;;
            *)
                repo_list_file_name=~/.$script/$repo_list_name.list
                ;;
        esac
        for repo_dir_name in `cat $repo_list_file_name`; do
            git -C $repo_dir_name $command
        done
        ;;
    *) echo "$script: unknown command"
       exit $E_PARAM
       ;;
esac
